---
jobs:
- name: build-centos-5
  max_in_flight: 1
  plan:
  - timeout: 3h
    do:
    - get: pljava_src
    - put: centos-5-untested-resource
      params:
        build: "."
        dockerfile: pljava/concourse/images/images/centos/5/Dockerfile
    - task: image-testing
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            username: {{docker-username}}
            password: {{docker-password}}
            repository: pivotaldata/pljava_centos
            tag: 5-untested
        inputs:
        - name: toolsmiths-images
        run:
          path: pljava/concourse/images/images/centos/5/test.sh
    - put: centos-5-resource
      params:
        pull_repository: pivotaldata/pljava_centos
        pull_tag: 5-untested
resources:
- name: pljava_src
  type: git
  source:
    uri: https://github.com/greenplum-db/pljava.git
    branch: docker_image_pipeline
- name: centos-5-untested-resource
  type: docker-image
  source:
    username: {{docker-username}}
    password: {{docker-password}}
    repository: pivotaldata/pljava_centos
    tag: 5-untested
- name: centos-5-resource
  type: docker-image
  source:
    username: {{docker-username}}
    password: {{docker-password}}
    repository: pivotaldata/pljava_centos
    tag: '5'
