---
jobs:
- name: build-centos-5
  max_in_flight: 1
  plan:
  - timeout: 3h
    do:
    - get: toolsmiths-images
      trigger: true
    - put: centos-5-untested-resource
      params:
        build: "."
        dockerfile: toolsmiths-images/images/centos/5/Dockerfile
    - task: image-testing
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            username: {{docker-username}}
            password: {{docker-password}}
            repository: pivotaldata/centos
            tag: 5-untested
        inputs:
        - name: toolsmiths-images
        run:
          path: toolsmiths-images/images/centos/5/test.sh
    - put: centos-5-resource
      params:
        pull_repository: pivotaldata/centos
        pull_tag: 5-untested
resources:
- name: toolsmiths-images
  type: git
  source:
    uri: git@github.com:Pivotal-DataFabric/toolsmiths-images.git
    branch: master
    private_key: {{toolsmiths-images-repo-key}}
- name: centos-5-untested-resource
  type: docker-image
  source:
    username: {{docker-username}}
    password: {{docker-password}}
    repository: pivotaldata/centos
    tag: 5-untested
- name: centos-5-resource
  type: docker-image
  source:
    username: {{docker-username}}
    password: {{docker-password}}
    repository: pivotaldata/centos
    tag: '5'
