## ======================================================================
## groups
## ======================================================================
groups:
- name: ALL
  jobs:
    - pljava_mvn_prepare_gpdb4
    - pljava_gpdb4_centos5_build
    - pljava_gpdb4_sles11_build
    - pljava_gpdb4_centos5_test
    - pljava_gpdb4_sles11_test
    - pljava_mvn_prepare_gpdb5
    - pljava_centos6_build
    - pljava_centos7_build
    - pljava_sles11_build
    - pljava_centos6_test
    - pljava_centos7_test
    - pljava_sles11_test

- name: GPDB4
  jobs:
    - pljava_mvn_prepare_gpdb4
    - pljava_gpdb4_centos5_build
    - pljava_gpdb4_sles11_build
    - pljava_gpdb4_centos5_test
    - pljava_gpdb4_sles11_test

- name: GPDB5
  jobs:
    - pljava_mvn_prepare_gpdb5
    - pljava_centos6_build
    - pljava_centos7_build
    - pljava_sles11_build
    - pljava_centos6_test
    - pljava_centos7_test
    - pljava_sles11_test

## ======================================================================
## resources
## ======================================================================
resources:

## GPDB4 resource
##
- name: bin_gpdb4_centos5
  type: s3
  source:
    bucket: {{gpdb4-bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{gpdb4-bucket-access-key-id}}
    secret_access_key: {{gpdb4-bucket-secret-access-key}}
    versioned_file: bin_gpdb_centos/bin_gpdb.tar.gz

- name: bin_gpdb4_sles11
  type: s3
  source:
    bucket: {{gpdb4-bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{gpdb4-bucket-access-key-id}}
    secret_access_key: {{gpdb4-bucket-secret-access-key}}
    versioned_file: bin_gpdb_sles/bin_gpdb.tar.gz

- name: pljava_centos5_img
  type: docker-image
  source:
    repository: pivotaldata/pljava_centos5_ci
    tag: 'latest'

- name: m2repository_centos5
  type: s3
  source:
    bucket: {{pl-bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: build/gpdb4/pljava/mvn/m2repository_centos5.tar.gz

- name: m2repository_sles11_gpdb4
  type: s3
  source:
    bucket: {{pl-bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: build/gpdb4/pljava/mvn/m2repository_sles11.tar.gz

- name: pljava_gpdb4_centos5_build
  type: s3
  source:
    bucket: {{pl-bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    regexp: build/gpdb4/pljava/centos5/pljava-(.*).gppkg

- name: pljava_gpdb4_sles11_build
  type: s3
  source:
    bucket: {{pl-bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    regexp: build/gpdb4/pljava/sles11/pljava-(.*).gppkg

- name: pljava_gpdb4_centos5_release
  type: s3
  source:
    bucket: {{pl-bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    regexp: release/gpdb4/pljava-(.*).gppkg

- name: pljava_gpdb4_sles11_release
  type: s3
  source:
    bucket: {{pl-bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    regexp: release/gpdb4/pljava-(.*).gppkg

## GPDB5 resource
##
- name: bin_gpdb_centos6
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: bin_gpdb_centos/bin_gpdb.tar.gz

- name: bin_gpdb_centos7
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: bin_gpdb_centos7/bin_gpdb.tar.gz

- name: bin_gpdb_sles11
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: bin_gpdb_sles11/bin_gpdb.tar.gz

- name: pljava_centos7_img
  type: docker-image
  source:
    repository: pivotaldata/pljava_centos7_ci
    tag: 'latest'

- name: pljava_centos6_img
  type: docker-image
  source:
    repository: pivotaldata/pljava_centos6_ci
    tag: 'latest'

- name: pljava_sles11_img
  type: docker-image
  source:
    repository: pivotaldata/plc_gpdb_sles11sp4
    tag: 'latest'

- name: pljava_src
  type: git
  source:
    branch: gpdb5_pljava
    uri: https://github.com/greenplum-db/pljava.git

- name: m2repository_centos7
  type: s3
  source:
    bucket: {{pl-bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: build/gpdb5/pljava/mvn/m2repository_centos7.tar.gz

- name: m2repository_centos6
  type: s3
  source:
    bucket: {{pl-bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: build/gpdb5/pljava/mvn/m2repository_centos6.tar.gz

- name: m2repository_sles11
  type: s3
  source:
    bucket: {{pl-bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: build/gpdb5/pljava/mvn/m2repository_sles11.tar.gz

- name: pljava_gpdb_centos6_build
  type: s3
  source:
    bucket: {{pl-bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    regexp: build/gpdb5/pljava/centos6/pljava-(.*).gppkg

- name: pljava_gpdb_centos7_build
  type: s3
  source:
    bucket: {{pl-bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    regexp: build/gpdb5/pljava/centos7/pljava-(.*).gppkg

- name: pljava_gpdb_sles11_build
  type: s3
  source:
    bucket: {{pl-bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    regexp: build/gpdb5/pljava/sles11/pljava-(.*).gppkg

- name: pljava_gpdb_centos6_release
  type: s3
  source:
    bucket: {{pl-bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    regexp: release/gpdb5/pljava-(.*).gppkg

- name: pljava_gpdb_centos7_release
  type: s3
  source:
    bucket: {{pl-bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    regexp: release/gpdb5/pljava-(.*).gppkg

- name: pljava_gpdb_sles11_release
  type: s3
  source:
    bucket: {{pl-bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    regexp: release/gpdb5/pljava-(.*).gppkg


jobs:
## GPDB4 PL/Java Jobs
##
- name: pljava_mvn_prepare_gpdb4
  plan:
  - aggregate:
    - get: pljava_src
      trigger: true
    - get: bin_gpdb4_centos5
    - get: pljava_centos5_img
    - get: bin_gpdb4_sles11
    - get: pljava_sles11_img
  - aggregate:
    - task: prepare_mvn_centos5
      file: pljava_src/concourse/tasks/prepare_mvn.yml
      image: pljava_centos5_img
      input_mapping:
        bin_gpdb: bin_gpdb4_centos5
      output_mapping:
        m2repository: m2repository_centos5
      params:
        OSVER: centos5
    - task: prepare_mvn_sles11
      file: pljava_src/concourse/tasks/prepare_mvn.yml
      image: pljava_sles11_img
      input_mapping:
        bin_gpdb: bin_gpdb4_sles11
      output_mapping:
        m2repository: m2repository_sles11
      params:
        OSVER: sles11
  - aggregate:
    - put: m2repository_centos5
      params:
        file: m2repository_centos5/m2repository_centos5.tar.gz
    - put: m2repository_sles11_gpdb4
      params:
        file: m2repository_sles11/m2repository_sles11.tar.gz

- name: pljava_gpdb4_centos5_build
  plan:
  - aggregate:
    - get: pljava_src
      passed: [pljava_mvn_prepare_gpdb4]
    - get: m2repository
      resource: m2repository_centos5
      passed: [pljava_mvn_prepare_gpdb4]
      trigger: true
    - get: bin_gpdb
      resource: bin_gpdb4_centos5
      passed: [pljava_mvn_prepare_gpdb4]
    - get: pljava_centos5_img
  - aggregate:
    - task: pljava_gpdb4_build
      file: pljava_src/concourse/tasks/build_pljava.yml
      image: pljava_centos5_img
      params:
        OSVER: centos5
  - aggregate:
    - put: pljava_gpdb4_centos5_build
      params:
        file: pljava_gppkg/pljava-*.gppkg

- name: pljava_gpdb4_sles11_build
  plan:
  - aggregate:
    - get: pljava_src
      passed: [pljava_mvn_prepare_gpdb4]
    - get: m2repository
      resource: m2repository_sles11_gpdb4
      passed: [pljava_mvn_prepare_gpdb4]
      trigger: true
    - get: bin_gpdb
      resource: bin_gpdb4_sles11
      passed: [pljava_mvn_prepare_gpdb4]
    - get: pljava_sles11_img
  - aggregate:
    - task: pljava_gpdb_build
      file: pljava_src/concourse/tasks/build_pljava.yml
      image: pljava_sles11_img
      params:
        OSVER: sles11
  - aggregate:
    - put: pljava_gpdb4_sles11_build
      params:
        file: pljava_gppkg/pljava-*.gppkg

- name: pljava_gpdb4_centos5_test
  plan:
  - aggregate:
    - get: pljava_src
      passed: [pljava_gpdb4_centos5_build]
    - get: pljava_bin
      resource: pljava_gpdb4_centos5_build
      trigger: true
      passed: [pljava_gpdb4_centos5_build]
    - get: bin_gpdb
      resource: bin_gpdb4_centos5
    - get: pljava_centos5_img
  - aggregate:
    - task: test_pljava
      file: pljava_src/concourse/tasks/test_pljava.yml
      image: pljava_centos5_img
      params:
        OSVER: centos5
  - aggregate:
    - put: pljava_gpdb4_centos5_release
      params:
        file: pljava_gppkg/pljava-*.gppkg

- name: pljava_gpdb4_sles11_test
  plan:
  - aggregate:
    - get: pljava_src
      passed: [pljava_gpdb4_sles11_build]
    - get: pljava_bin
      resource: pljava_gpdb4_sles11_build
      trigger: true
      passed: [pljava_gpdb4_sles11_build]
    - get: bin_gpdb
      resource: bin_gpdb4_sles11
    - get: pljava_sles11_img
  - aggregate:
    - task: test_pljava
      file: pljava_src/concourse/tasks/test_pljava.yml
      image: pljava_sles11_img
      params:
        OSVER: sles11
  - aggregate:
    - put: pljava_gpdb4_sles11_release
      params:
        file: pljava_gppkg/pljava-*.gppkg

## GPDB5 PL/Java Jobs
##
- name: pljava_mvn_prepare_gpdb5
  plan:
  - aggregate:
    - get: pljava_src
      trigger: true
    - get: bin_gpdb_centos7
    - get: bin_gpdb_centos6
    - get: bin_gpdb_sles11
    - get: pljava_centos7_img
    - get: pljava_centos6_img
    - get: pljava_sles11_img
  - aggregate:
    - task: prepare_mvn_centos7
      file: pljava_src/concourse/tasks/prepare_mvn.yml
      image: pljava_centos7_img
      input_mapping:
        bin_gpdb: bin_gpdb_centos7
      output_mapping:
        m2repository: m2repository_centos7
      params:
        OSVER: centos7
    - task: prepare_mvn_centos6
      file: pljava_src/concourse/tasks/prepare_mvn.yml
      image: pljava_centos6_img
      input_mapping:
        bin_gpdb: bin_gpdb_centos6
      output_mapping:
        m2repository: m2repository_centos6
      params:
        OSVER: centos6
    - task: prepare_mvn_sles11
      file: pljava_src/concourse/tasks/prepare_mvn.yml
      image: pljava_sles11_img
      input_mapping:
        bin_gpdb: bin_gpdb_sles11
      output_mapping:
        m2repository: m2repository_sles11
      params:
        OSVER: sles11
  - aggregate:
    - put: m2repository_centos7
      params:
        file: m2repository_centos7/m2repository_centos7.tar.gz
    - put: m2repository_centos6
      params:
        file: m2repository_centos6/m2repository_centos6.tar.gz
    - put: m2repository_sles11
      params:
        file: m2repository_sles11/m2repository_sles11.tar.gz

- name: pljava_centos7_build
  plan:
  - aggregate:
    - get: pljava_src
      passed: [pljava_mvn_prepare_gpdb5]
    - get: m2repository
      resource: m2repository_centos7
      passed: [pljava_mvn_prepare_gpdb5]
      trigger: true
    - get: bin_gpdb
      resource: bin_gpdb_centos7
      passed: [pljava_mvn_prepare_gpdb5]
    - get: pljava_centos7_img
  - aggregate:
    - task: pljava_gpdb_build
      file: pljava_src/concourse/tasks/build_pljava.yml
      image: pljava_centos7_img
      params:
        OSVER: centos7
  - aggregate:
    - put: pljava_gpdb_centos7_build
      params:
        file: pljava_gppkg/pljava-*.gppkg

- name: pljava_centos6_build
  plan:
  - aggregate:
    - get: pljava_src
      passed: [pljava_mvn_prepare_gpdb5]
    - get: m2repository
      resource: m2repository_centos6
      passed: [pljava_mvn_prepare_gpdb5]
      trigger: true
    - get: bin_gpdb
      resource: bin_gpdb_centos6
      passed: [pljava_mvn_prepare_gpdb5]
    - get: pljava_centos6_img
  - aggregate:
    - task: pljava_gpdb_build
      file: pljava_src/concourse/tasks/build_pljava.yml
      image: pljava_centos6_img
      params:
        OSVER: centos6
  - aggregate:
    - put: pljava_gpdb_centos6_build
      params:
        file: pljava_gppkg/pljava-*.gppkg

- name: pljava_sles11_build
  plan:
  - aggregate:
    - get: pljava_src
      passed: [pljava_mvn_prepare_gpdb5]
    - get: m2repository
      resource: m2repository_sles11
      passed: [pljava_mvn_prepare_gpdb5]
      trigger: true
    - get: bin_gpdb
      resource: bin_gpdb_sles11
      passed: [pljava_mvn_prepare_gpdb5]
    - get: pljava_sles11_img
  - aggregate:
    - task: pljava_gpdb_build
      file: pljava_src/concourse/tasks/build_pljava.yml
      image: pljava_sles11_img
      params:
        OSVER: sles11
  - aggregate:
    - put: pljava_gpdb_sles11_build
      params:
        file: pljava_gppkg/pljava-*.gppkg

- name: pljava_centos7_test
  plan:
  - aggregate:
    - get: pljava_src
      passed: [pljava_centos7_build]
    - get: pljava_bin
      resource: pljava_gpdb_centos7_build
      passed: [pljava_centos7_build]
      trigger: true
    - get: bin_gpdb
      resource: bin_gpdb_centos7
    - get: pljava_centos7_img
  - aggregate:
    - task: test_pljava
      file: pljava_src/concourse/tasks/test_pljava.yml
      image: pljava_centos7_img
      params:
        OSVER: centos7
  - aggregate:
    - put: pljava_gpdb_centos7_release
      params:
        file: pljava_gppkg/pljava-*.gppkg

- name: pljava_centos6_test
  plan:
  - aggregate:
    - get: pljava_src
      passed: [pljava_centos6_build]
    - get: pljava_bin
      resource: pljava_gpdb_centos6_build
      trigger: true
      passed: [pljava_centos6_build]
    - get: bin_gpdb
      resource: bin_gpdb_centos6
    - get: pljava_centos6_img
  - aggregate:
    - task: test_pljava
      file: pljava_src/concourse/tasks/test_pljava.yml
      image: pljava_centos6_img
      params:
        OSVER: centos6
  - aggregate:
    - put: pljava_gpdb_centos6_release
      params:
        file: pljava_gppkg/pljava-*.gppkg

- name: pljava_sles11_test
  plan:
  - aggregate:
    - get: pljava_src
      passed: [pljava_sles11_build]
    - get: pljava_bin
      resource: pljava_gpdb_sles11_build
      trigger: true
      passed: [pljava_sles11_build]
    - get: bin_gpdb
      resource: bin_gpdb_sles11
    - get: pljava_sles11_img
  - aggregate:
    - task: test_pljava
      file: pljava_src/concourse/tasks/test_pljava.yml
      image: pljava_sles11_img
      params:
        OSVER: sles11
  - aggregate:
    - put: pljava_gpdb_sles11_release
      params:
        file: pljava_gppkg/pljava-*.gppkg

