platform: linux

image_resource:
  type: docker-image

inputs:
  - name: bin_gpdb
  - name: pljava_src

outputs:
  - name: m2repository

run:
  path: pljava_src/concourse/scripts/prepare_mvn.sh
params:
  OSVER:
