platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotaldata/pljava_centos7_ci
    tag: 'latest'

inputs:
  - name: bin_gpdb
  - name: pljava_src
  - name: pljava_bin

run:
  path: pljava_src/concourse/scripts/test_pljava.sh

params: 
  OSVER:
